name: surveyapp-BE

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        volumes:
          - mongodb-data:/data/db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Start MongoDB
        run: docker-compose up -d

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Stop MongoDB
        run: docker-compose down

volumes:
  mongodb-data:
